name: Manage Issues
on:
  schedule:
    - cron: "0 9 * * *"
jobs:
  manage-stale-issues:
    name: Manage Stale Issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label and/or close stale issues
        uses: actions/stale@v8
        with:
          days-before-issue-stale: 30
          days-before-pr-stale: -1
          days-before-close: 7
          stale-issue-label: "stale"
          remove-stale-when-updated: true
          close-issue-reason: "not_planned"
          close-issue-message: "This issue has been closed due to inactivity."
